feedhenry/fh-fhc

lib/cmd/fh3/admin/mbaas/bearertoken.js
Note that this is PR'ed to the FHMAP-224 branch
=> Add command to get a new bearer token for an mBaas

CHANGELOG.md, lib/common.js, package.json
to reduce the amount of polling from fhc we want to increase the interval for how often it polls
=> increase polling interval

lib/cmd/fh3/app/_baseCloudRequest.js, lib/cmd/fh3/appforms/environments/submissions/addfile.js, lib/cmd/fh3/appforms/environments/submissions/exportcsv.js, lib/cmd/fh3/appforms/environments/submissions/exportpdf.js, lib/cmd/fh3/appforms/environments/submissions/getfile.js, lib/cmd/fh3/appforms/environments/submissions/updatefile.js, lib/cmd/fh3/appforms/projects/create.js, lib/cmd/fh3/appforms/projects/list.js, lib/cmd/fh3/appforms/projects/read.js, lib/cmd/fh3/appforms/projects/update.js, lib/cmd/fh3/appforms/templates/forms/import.js, lib/cmd/fh3/appforms/templates/forms/list.js, lib/cmd/fh3/appforms/templates/forms/read.js, lib/cmd/fh3/appforms/templates/themes/import.js, lib/cmd/fh3/appforms/templates/themes/list.js, lib/cmd/fh3/appforms/templates/themes/read.js, lib/utils/request.js, npm-shrinkwrap.json, package.json
APIs for CRUD operations for a forms project
=> Added forms project APIs

lib/cmd/common/version.js, lib/cmd/fhc/target.js, lib/fhc.js, package.json
Added A Check To FHC to verify that the platform target is at least a certain version.
=> Added Platform Target Check

CHANGELOG.md, lib/cmd/fh3/app/create.js, npm-shrinkwrap.json, package.json
Needs the "type" and "imported" parameters in order to import from a git repo.
=> Fixed app import parameters

CHANGELOG.md, Gruntfile.js, lib/cmd/common/version.js, npm-shrinkwrap.json, package.json
* Set publish tag to `latest-1`
* Look for `latest-1` tag when checking for updates
* Change -BUILD-NUMBER to +BUILD-NUMBER
=> RHMAP-2648

CHANGELOG.md, lib/cmd/common/apps.js, lib/cmd/common/import.js, lib/cmd/common/templates.js, lib/cmd/fh2/app/create.js, lib/cmd/fh3/app/create.js, lib/cmd/fh3/app/stage.js, lib/cmd/fh3/projects.js, lib/cmd/fh3/services.js, npm-shrinkwrap.json, package.json
* allow specify the deploy environment when create projects/app/services
* allow set if auto deploy should be enabled when deploy apps
=> Rhmap 2746 deploy environment on creation

lib/cmd/common/version.js, package.json
* use the new ngui endpoint to get the proper platform version to compare.
=> fix an issue with fhc target

CHANGELOG.md, lib/cmd/common/import.js, lib/cmd/fh2/app/create.js, lib/cmd/fh3/projects.js, lib/cmd/fh3/services.js, lib/utils/ini.js, package.json
* when creating projects/services/apps, the environment should be optional
=> Optional environments when create projects

CHANGELOG.md, lib/cmd/fh3/app/stage.js, package.json
* post data to the deploy endpoint
=> fix an issue with auto deploy when stage apps

package.json, sonar-project.properties
=> Sonar Props file

CHANGELOG.md, Gruntfile.js, lib/cmd/fh3/appforms/data-sources/create.js, lib/cmd/fh3/appforms/data-sources/list.js, lib/cmd/fh3/appforms/data-sources/read.js, lib/cmd/fh3/appforms/data-sources/remove.js, lib/cmd/fh3/appforms/data-sources/update.js, lib/cmd/fh3/appforms/environments/data-sources/list.js, lib/cmd/fh3/appforms/environments/data-sources/read.js, lib/cmd/fh3/appforms/environments/data-sources/refresh.js, lib/cmd/fh3/appforms/environments/data-sources/validate.js, lib/cmd/fh3/services.js, lib/common.js, lib/genericCommand.js, lib/utils/request.js, npm-shrinkwrap.json, package.json, test/accept/test_as_cli.js, test/fixtures/appforms/fixture_data_source.js, test/fixtures/appforms/fixture_data_sources.js, test/fixtures/appforms/fixture_env_data_sources.js, test/unit/fh3/appforms/data_sources/test_data_sources.js, test/unit/fh3/appforms/environments/data_sources/test_env_data_sources.js
Added APIs to deal with Data Sources on the Core Platform and MBaaSes.
=> Added New Data Source APIs

lib/cmd/fh3/app/logs/tail.js, npm-shrinkwrap.json, package.json
Integrating @alanmoran changes as separate PR.
=> RHMAP-4881 - Cannot tail logs by name

lib/cmd/fh3/app/stage.js, npm-shrinkwrap.json, package.json
Unit tests are committed from this since I can't see a common pattern for tests in the current project and didn't want to add something that wasn't a fit.
=> add the ability to pass branch information to fh3 stage command

lib/cmd/common/build.js
Quick fix for bug introduced in the refactoring for this issue.
Tested it manually against `eng1` to confirm it reproduces correct behavior from <2.4.1
=> [RHMAP-5022] Fix argsToPayload regression

lib/cmd/fh3/appforms/forms/export.js, lib/cmd/fh3/appforms/forms/import.js, lib/utils/request.js, npm-shrinkwrap.json, package.json, sonar-project.properties, test/fixtures/appforms/fixture_forms.js, test/unit/fh3/appforms/test_forms.js
Contains the content in PRs #192 and #193, also added unit test coverage for not overwriting files on `export` and some linting style fixes and version bump.
ping @corinnekrych @vchepeli @wei-lee @wtrocki @pb82
=> [RHMAP 5251] FHC Command to import/export forms

CHANGELOG.md, lib/cmd/fh3/appforms/data-sources/create.js, lib/cmd/fh3/appforms/data-sources/list.js, lib/cmd/fh3/appforms/data-sources/read.js, lib/cmd/fh3/appforms/data-sources/remove.js, lib/cmd/fh3/appforms/data-sources/update.js, lib/cmd/fh3/appforms/environments/data-sources/audit-logs.js, lib/cmd/fh3/appforms/environments/data-sources/list.js, lib/cmd/fh3/appforms/environments/data-sources/read.js, lib/cmd/fh3/appforms/environments/data-sources/refresh.js, lib/cmd/fh3/appforms/environments/data-sources/validate.js, lib/cmd/fh3/appforms/forms/export.js, lib/cmd/fh3/appforms/forms/import.js, lib/cmd/fh3/services.js, lib/common.js, lib/genericCommand.js, lib/utils/request.js, npm-shrinkwrap.json, package.json, sonar-project.properties, test/accept/test_as_cli.js, test/fixtures/appforms/fixture_data_source.js, test/fixtures/appforms/fixture_data_sources.js, test/fixtures/appforms/fixture_env_data_sources.js, test/fixtures/fixture_service.js, test/fixtures/fixture_services.js, test/unit/fh3/appforms/data_sources/test_data_sources.js, test/unit/fh3/appforms/environments/data_sources/test_env_data_sources.js, test/unit/fh3/services/test_services.js
Appforms Back End Integration Feature Branch.
=> Fh 1722 appforms back end integration 

lib/cmd/fh3/app/create.js, package.json
I wasn't getting any data in fhc.app.create callback, this fix works.
JIRA: https://issues.jboss.org/browse/RHMAP-5714
=> Fix callback from app.create (wasn't passing params)

package.json
=> Bump _minPlatformVersion

lib/cmd/fhc/login.js, lib/utils/proxy.js, lib/utils/request.js, package.json, sonar-project.properties
Will not use a request proxy unless it is set on FHC config (fhc fhcfg).
[RHMAP-6397](https://issues.jboss.org/browse/RHMAP-6397)
=> Fix proxy issue when signing int to OpenShift Online Trials server.

lib/cmd/fh3/appdata.js, lib/common.js, package.json, sonar-project.properties
https://issues.jboss.org/browse/RHMAP-6448
=> RHMAP-6448 - Create export related commands using dummy data from supercercore

lib/cmd/fh3/appdata/export/status.js, npm-shrinkwrap.json, package.json, sonar-project.properties
The `appdata export status` command should not poll jobs that have failed. Exit with an appropriate error message.
ping @trepel @ziccardi @wei-lee
=> Rhmap 7754

lib/cmd/fh3/appdata/import/list.js, lib/cmd/fh3/appdata/import/read.js, lib/cmd/fh3/appdata/import/start.js, lib/cmd/fh3/appdata/import/status.js, lib/cmd/fh3/appforms/forms/import.js, lib/utils/request.js, npm-shrinkwrap.json, package.json, sonar-project.properties
We need to add the command to FHC to enable the app data importing feature on the client side.
Added the following command:
- import list
- import read
- import tart
- import status
=> RHMAP-6005 Added import commands

lib/cmd/fh3/appdata/export/download.js, lib/cmd/fh3/appdata/export/list.js, lib/cmd/fh3/appdata/export/read.js, lib/cmd/fh3/appdata/export/start.js, lib/cmd/fh3/appdata/export/status.js, package.json
Added some missing i18n support for  commands which has been changed since the previous PR.
=> RHMAP-5465: another i18n support for commands

README.md, doc/fh3/app/create.md, lib/cmd/fh3/app/create.js
* Added --type as a required argument across the documentation.
* Added the correct way of specifying a branch.
* Added documentation to previously undocumented arguments for the create command.
ping @witmicko @pb82
=> improve command usage instructions

lib/cmd/fh3/app/create.js, npm-shrinkwrap.json, package.json, sonar-project.properties
=> version bump

lib/cmd/common/build.js, npm-shrinkwrap.json, package.json, sonar-project.properties, test/unit/legacy/test_build.js
@wei-lee @pb82 
[RHMAP-3935](https://issues.jboss.org/browse/RHMAP-3935)
environment argument is required,
better description for `tag` argument
#related PR
https://github.com/fheng/millicore/pull/725
=> Rhmap 3935 fhc builds are not in history

lib/cmd/common/build.js, npm-shrinkwrap.json, package.json, sonar-project.properties
@wei-lee @pb82 
missing parameter was sent in payload as 'undefined'
=> Rhmap 5323 i os bundle without password fails

package.json
=> update node js engines

lib/cmd/fh3/admin/mbaas/create.js, npm-shrinkwrap.json, package.json, sonar-project.properties
@psturc Do you have time to review and verify this small change?
=> Remove username and password as required args. Require MBaaS type

lib/cmd/common/git.js, lib/common.js, package.json, sonar-project.properties
`fhc git props` & `fhc git set` have been broken with a while, this patches and fixes the commands.
Some commands to test with below.
Reading git props for an app:
```
fhc git props 6magpwla4zuxssywj77u6o2x
```
Setting a default branch for an app:
```
fhc git set 6magpwla4zuxssywj77u6o2x branch master
```
=> Fixing git prop set

LICENSE
Missing year and name from copyright license
=> RHMAP-8199 - Updated license

LICENSE
Remove appendix in license.
@laurafitzgerald once last final read ;)
=> RHMAP-8199 - Update license..again

lib/cmd/common/import.js, package.json, sonar-project.properties
Fixes this issue https://issues.jboss.org/browse/RHMAP-880
Use recommended approach to send form data.
(The previous approach should actually work as well according to documentation. https://github.com/request/request#multipartform-data-multipart-form-uploads)
=> Fixed import of zip file

doc/common/build.md, lib/cmd/common/build.js
@pb82 This is the new PR. Have some time for review? :)
=> Minor fixes in fhc build docs

lib/cmd/fh3/cordova/migrate.js, npm-shrinkwrap.json, package.json, sonar-project.properties, test/fixtures/cordova/fixture_migrate.js, test/unit/fh3/cordova/migrate_test.js
=> fhc cordova migrate command

lib/cmd/fh3/cordova/migrate.js
@jhellar do you mind a review?
=> Rhmap 11827.cordova.migrate.help.info

Gruntfile.js, package.json
There was a bug in grunt-zanata-js and was caused a build issue. this PR is to update the deps of grunt-zanata-js which contains a fix for that.
=> Update deps grunt zanata js

lib/utils/request.js, npm-shrinkwrap.json, package.json, sonar-project.properties
Added request message to try logging in again after authentication errors.
@wtrocki
=> RHMAP-15101 - added log message

test/fixtures/admin/fixture_teams.js, test/fixtures/admin/myteam.json, test/fixtures/admin/teams.json, test/unit/fh3/admin/test_teams.js
JIRA: https://issues.jboss.org/browse/RHMAP-15719
=> RHMAP-15719 - Add unit tests for admin teams commands

lib/cmd/fh3/services/list.js, test/fixtures/services/fixture_services.js, test/unit/fh3/services/test_services.js
JIRA: https://issues.jboss.org/browse/FH-3652
Following the local test.
=> RHMAP-16030 - fhc services list --json doesn't work properly

lib/cmd/fh3/artifacts.js, test/fixtures/fixture_artifacts.js, test/unit/fh3/test_artifacts.js
JIRA: https://issues.jboss.org/browse/RHMAP-15722
**Following the changes.**
* Add the V3 standard 
* Remove the parameter that was never used ( project )
* Add unit tests
**Important: Not found automated tests for it.** 
**Following the local test.**
=> RHMAP-15722 - Add command `fhc artifacts` to V3 standard and add unit test

lib/cmd/fhc/help.js
JIRA: https://issues.jboss.org/browse/FH-3782
**Motivation** Shows the usage of the commands without the error. 
The following image before to do this fix. 
The following image after to do this fix.
=> FH-3782 - FHC shows help usage as error when it should not be

lib/cmd/fh3/env/push.js, package.json, sonar-project.properties
Motivation: Case bug
JIRA: https://issues.jboss.org/browse/RHMAP-17055
=> Rhmap 17055 - fhc env push command does not work on dedicated environment

lib/cmd/common/build.js, lib/cmd/common/version.js, npm-shrinkwrap.json, package.json
generate PR code
Small changes required to get fhc build to work with self-managed build farm.
1. Correctly resolve the url of artifacts and print them out
2. Print out QR code.
* fhc build should continue to work with a cluster that is using the SAAS build farm
* try fhc build again with this project in OSM4: https://osm4-rhmap.osm4.skunkhenry.com/#projects/xmd2inzuf5kakpmvetwtlku4/apps. It should work as well.
=>  ✨  update fhc build to work with self-managed build farm. Also

lib/cmd/fh2/app/create.js, lib/cmd/fh3/app/create.js, lib/cmd/fh3/projects/create.js, lib/cmd/fh3/services/create.js, lib/cmd/fh3/templates/apps.js, lib/cmd/fh3/templates/projects.js, lib/cmd/fh3/templates/services.js
JIRA: https://issues.jboss.org/browse/FH-3830
**Motivation**: Fix the PR https://github.com/feedhenry/fh-fhc/pull/369.
**Steps to verify**
fhc templates apps <template-id>
fhc templates projects <template-id>
fhc templates services <template-id>
fhc projects create --title=<title>
fhc services create --title=<title>
fhc apps create <projectId> --title=<title>
**Following the local tests.** 
To create a app
```
dhcp-17-108:fh-fhc cmacedo$ ./bin/fhc.js app create k2654bvzrmaebx7ocnwtzxfp  --title="test4" --type=cloud_nodejs
{
"scmCacheKey": "7cb34dd6479be4263d1acaf3089d6372",
"hierarchy": null,
"description": "",
"domain": "support",
"type": "cloud_nodejs",
"openshift": null,
"openshift3": null,
"scmCommit": null,
"jsonTemplateId": "hello_world_mbaas_instance",
"template": null,
"email": …
```
=> Fh 3830 - Error to create project, service and application after changes made into the templates

lib/cmd/fh3/connections/list.js, lib/cmd/fh3/connections/read.js, lib/cmd/fh3/connections/update.js, npm-shrinkwrap.json, package.json, sonar-project.properties
JIRA: https://issues.jboss.org/browse/FH-3886
**Motivation**
Adapt output to follow the standard and work on console and as a dependency.
=> FH-3886 - Adapt output of fhc connections command

CONTRIBUTING.md
JIRA: https://issues.jboss.org/browse/FH-3790
=> FH-3790: Add requirement to bumped the version into the CONTRIBUTION doc of these project

lib/utils/exec.js, npm-shrinkwrap.json, package.json, sonar-project.properties
=> Replace deprecated `util.pump`

lib/cmd/fh3/version.js, npm-shrinkwrap.json, package.json, sonar-project.properties
The #314 was outdated and with conflicts. So, I just create a new PR with this small change which was easier than fixing the PR.
**Motivation**
Timeout to support env var or default to 15secs
=> Ref. Change proxy timeout to millicore PR 314

lib/cmd/fh3/projects/list.js, npm-shrinkwrap.json, package.json, sonar-project.properties, test/fixtures/projects/fixture_projects.js, test/fixtures/projects/list_responses.js, test/unit/fh3/projects/test_projects.js
don't include apps info by default when listing projects (because it can take a long time)
=> Rhmap 18901

README.md, npm-shrinkwrap.json, package.json, sonar-project.properties
JIRA: https://issues.jboss.org/browse/FH-4126
=> FH-4126 - Update Readme after restructuration

lib/cmd/fh3/ups/config.js, lib/cmd/fh3/ups/read.js, lib/cmd/fh3/ups/reset.js, lib/cmd/fh3/ups/send.js, lib/cmd/fh3/ups/variant/add.js, lib/cmd/fh3/ups/variant/delete.js, lib/cmd/fh3/ups/variant/list.js, lib/common.js, lib/utils/request.js, npm-shrinkwrap.json, package.json, sonar-project.properties, test/unit/fh3/ups/test_ups.js, test/unit/fh3/ups/variant/test_variant.js
LINK: https://issues.jboss.org/browse/RHMAP-1502
**Commands/Tests**
* Check the UPS commands (fhc help) - `./bin/fhc.js ups `
```
Camila:fh-fhc cmacedo$ ./bin/fhc.js ups 
No action specified. Usage: 
fhc ups <action>
Where <action> is one of:
config             	Read Push Notifications init config for an app
read               	Read the Push Notification for an app
reset              	Reset Push Notifications Secret for an app
send               	Send Push Notifications for an app
variant
add                	List Push Notifications Variants for an app
delete             	Delete Push Notifications Variant for an app
list               	List Push Notifications Variants for an app
Camila:fh-fhc cmacedo$ 
```
* UPS init config - `./bin/fhc.js ups config --app=<appId> `
* UPS read - …
=> RHMAP-1502 - Provide FHC CLI functionality for UPS

CHANGELOG.md, CONTRIBUTING.md, npm-shrinkwrap.json, package.json, sonar-project.properties
Update changelog as per [RHMAP-19216](https://issues.jboss.org/browse/RHMAP-19216). 
Changes:
- CHANGELOG.md updated
- note to update CHANGELOG.md added to README.md
- note re: commit message standard added to README.md
- version bumped to 4.2.1 (from 4.2.0)
=> Updates Changelog 

lib/common.js, npm-shrinkwrap.json, package.json, sonar-project.properties
**Motivation** 
The root cause of this error is when some values are not returned for the mbaas then the error occurs, which means that probably now the rest API is not so long return the properties empty. 
REF: https://issues.jboss.org/browse/RHMAP-19658
**Local Test**
=> RHMAP-19658 - Fix error when the output of the command 'fhc admin mbaas list' will be formatted

.github/pull_request_template.md
https://issues.jboss.org/browse/RHMAP-20969
Add PR template
Better quality in reviews
Adding a standard file
Not possible check before merge
=> task(RHMAP-20969): Add PR template to fh-fhc repo

CHANGELOG.md, lib/cmd/fh3/eventalert/create.js, lib/cmd/fh3/eventalert/delete.js, lib/cmd/fh3/eventalert/list.js, lib/cmd/fh3/eventalert/update.js, npm-shrinkwrap.json, package.json, test/unit/fh3/eventalert/test_eventalert.js
https://issues.jboss.org/browse/RHMAP-20968
Fix the bug in the alert commands. 
It is not a fixed value. Fix the bug.
Replace the fixed value by the function which returns the target domain
1. Run `./bin/fhc.js target <domain>` to target in a domain that is not the fixed one ( e.g ` bin/fhc.js target https://rhmap.osm1.skunkhenry.com/`)
2. Run `./bin/fhc.js login`
* Check the list command. Following the local test.
```
cmacedo@camilas-MacBook-Pro ~/work/fh-fhc (RHMAP-20968) $ ./bin/fhc.js eventalert list --app=r6ghddievqzumnsq2djvtruv  --env=dev 
┌──────────────────────────┬─────────────┬───────────────┬─────────┬───────────────────────┬────────────────────────┬─────────────────┐
│ ID                       │ Name        │ Emails        │ Enabled │ Categories            │ Names …
```
=> fix(RHMAP-20968): FHC alert commands are with domain value fixed

CHANGELOG.md
=> FIx text in CHANGELOG file

CHANGELOG.md, lib/cmd/fh3/build.js, lib/fhc.js, npm-shrinkwrap.json, package.json, po/fh-fhc.pot
https://issues.jboss.org/browse/RHMAP-21697
Add DEPRECATION NOTICE regards BF
It will not so long be supported after 31st Of December
- Add changelog info 
- Add info in the desc of the command. 
* Check if the DEPRECATION will show
in the help
* Check if the DEPRECATION will show in the command desc.
* Check if is shown the deprecation notice when the command is executed and when it face any error indeed the yargs args validation.
=> Add DEPRECATION NOTICE regards BF

CHANGELOG.md, README.md
https://issues.jboss.org/browse/RHMAP-21483
Updating files regard the publish
Because it contains the versions which were changed
=> Updating README and CHANGELOG with the info regards publish of new version
