- lib/cmd/common/-v.js
the -v option to display the version of the fh-fhc tool has been removed, it should be re-added.
The newer "version" command does not work directly after installation, since there is no target set
> FHCLI-3 - re-add '-v' option

- lib/genericCommand.js
- lib/utils/request.js
When using fh-fhc for the first time, there is not a current target.
executing the fhc version command produces an error
eg.
$ fhc version
fhc ERR! Error: getaddrinfo ENOTFOUND
fhc ERR!     at errnoException (dns.js:37:11)
fhc ERR!     at Object.onanswer [as oncomplete] (dns.js:124:16)
fhc ERR!
fhc ERR! System Darwin 14.0.0
fhc ERR! command "node" "/Users/mmurphy/node/current/bin/fhc" "version"
fhc not ok
The actual detail can vary, depending on client OS (helpdesk ticket refers to Windows)
A better message should be display, e.g. "need to target cloud platform first"
the apps command displays "$ fhc apps
fhc ERR! No user prefs! - 'You are not logged in. Login with fhc login <user> <passwd> or fhc keys user target <api-key>.'
fhc not ok"
> FHCLI-2 - when initial installed, "fhc version" command produces obscure error

- CHANGELOG.md
- lib/cmd/common/version.js
- package.json
Updated endpoint used to obtain platform version. Instead of using java milicore version we use now semver platform format exposed by gui node server. Added support for JSON format - needed to automate some specific tasks depending on platform version. When requesting JSON format we do not check for new tool upgrade (this will be used internally and we do not need that to be included in json)
> RHMAP-2482 - Expose semver version of core in fhc version

- lib/cmd/fh3/app/create.js
- package.json
During the load test, I discovered that the app creation command doesn't wait for app to be available (cloned by fh-scm). This means if the app is being deployed right after the creating, the deploy request will fail.
In order to allow my performance test, I added a wait flag to the app creating command.
> add wait flag for app creation

- lib/cmd/fh3/admin/mbaas/create.js
- lib/cmd/fh3/admin/mbaas/update.js
- lib/common.js
- npm-shrinkwrap.json
- package.json
- sonar-project.properties
To allow provide the "size" information when creating the mbaas targets via fhc. This is mainly to help ops to easily figure out what the sizes of the mbaases.
When create/update mbaases, an extra size field can be provided. When list mbaases, the size info is listed too.
https://issues.jboss.org/browse/RHMAP-4878
> add the extra size parameter when creating mbaases

- Gruntfile.js
- lib/cmd/fh3/admin/environments/create.js
- lib/common.js
- npm-shrinkwrap.json
- package.json
- sonar-project.properties
- test/fixtures/admin/environments.json
- test/fixtures/admin/fixture_environments.js
- test/unit/common/test_createTable.js
- test/unit/fh3/admin/test_environments.js
- test/unit/fh3/admin/test_environments_commands.js
This is a quite simple fix on the cli front-end. From @wei-lee's input I think accepting `undefined` on supercore is probably benign, but if time allows I'd like to guard it against that too, to get to know the module and the cluster deploy+testing procedure.
Added a couple tests at the unit level, that don't depend on mocking web calls. Hopefully to break out the table-creating functions from the huge `common.js` file.
> [RHMAP-4932] fhc admin environment create allows null/undefined - fix on fh-fhc

- lib/cmd/fh3/admin/environments/create.js
- npm-shrinkwrap.json
- package.json
Add new `noAppend` flag to support saving environment without adding it to the list of available environments. This command may be used when setting up new cluster and we want to properly
adjust permission levels for environments. 
`fhc admin environments create --id=test --label=test --targets=mbaas1 --noAppend`
ping @wei-lee @pb82
> RHMAP-3295 - noAppend flag for saving new enviroments.

- lib/cmd/fh3/app/logs/tail.js
- lib/genericCommand.js
- npm-shrinkwrap.json
- package.json
Allow to tail both error and stdout in one command. 
Solution is using list to fetch all logs and then selecting two most recent ones. 
This is workaround for current api limitations. 
Code inspired on another PR added by community member. 
Tailing 2 different files so logs can appear in different order 
ping @alanmoran, @pb82, @paolobueno, @ziccardi
> Added support for tailing error logs 

- lib/cmd/fh2/undeploy.js
- lib/cmd/fh3/app/undeploy.js
- npm-shrinkwrap.json
- package.json
- sonar-project.properties
- test/unit/fh3/app/test_undeploy.js
There are now two different version of the undeploy command:
- `lib/cmd/fh2/undeploy.js` works only with the old Feedhenry v2 Platform
- `lib/cmd/fh3/app/undeploy.js` is the new one that works with Feedhenry v3
The command syntax is:
`fhc app undeploy --id=<app-id> --env=<environment> --domain=<domain>`
ping @wtrocki @wei-lee
> RHMAP-4395 undeploy command now in fh2 and fh3

- lib/cmd/common/initlocal.js
Little fix on removing `console.log` I left in accidentally when debugging stuff manually.
Can I get a quick review, @wei-lee or @wtrocki? Does this change need to bump a version? The version bump on the original branch issue wasn't published to npm yet, only automatically to [npm.skunkhenry.com]()
> [RHMAP-5022] Remove debug logging

- lib/cmd/fh3/services.js
- lib/common.js
- npm-shrinkwrap.json
- test/fixtures/fixture_service.js
- test/fixtures/fixture_services.js
- test/unit/fh3/services/test_services.js
Testing Notes:
Deployed to npm.skunkhenry.com as version 2.5.0-221
Using a service: http://testing.ndonnellytest.skunkhenry.com/#services/deqrvgys6gboumo2fvckur76/apps/deqrvg5r2sfblq2ksgbmjy4i/details
1. Target http://testing.ndonnellytest.skunkhenry.com
2. Run fhc services data-sources deqrvgys6gboumo2fvckur76
It should return a table of data sources associated with the service.
> Using service read object to display table

- lib/cmd/common/build.js
- npm-shrinkwrap.json
- package.json
- sonar-project.properties
Adds support for new params `--commit` and `--branch`. It seems millicore can work with only the branch reference, and `commit` is only necessary when specifying a commit that's not on the head of the branch.
ping @wei-lee, @wtrocki, @vchepeli
> [RHMAP-4633] fhc build command has an unfriendly way of specifying branch

- lib/cmd/fh3/admin/mbaas/delete.js
- test/fixtures/admin/fixture_mbaas.js
- test/unit/fh3/admin/test_mbaas.js
Part of the changes to support the new mbaas targets models.
Reverting the disabling of `fhc admin mbaas delete`, pointing to the same JIRA as the first PR.
ping @pb82 @odra @wei-lee @vchepeli
> [RHMAP 5595] Reenable delete command for mbaas targets

- lib/cmd/common/build.js
- npm-shrinkwrap.json
- package.json
- sonar-project.properties
- test/fixtures/user/fixture_user_read.js
- test/unit/legacy/test_user.js
Revisiting [RHMAP-4633](https://issues.jboss.org/browse/RHMAP-4633), about improving the interface for specifying a git reference on the `fhc build` command, due to an incomplete initial implementation.
* During testing we discovered the back-end is building on top of the previously specified `gitRef` so for now a workaround of defaulting to `master` was added to make running the command deterministic.
* Add a `git-` prefix to the parameters because of collision with `tag`
> [RHMAP] 4633 - Fix gitref params and add support for tag

- lib/cmd/fh3/admin/mbaas/create.js
- lib/cmd/fh3/admin/mbaas/update.js
- npm-shrinkwrap.json
- package.json
- sonar-project.properties
- test/unit/fh3/admin/test_mbaas.js
fhc must be able to set the `editable` field of MBaaS targtes. This PR adds that ability to the following commands:
`fhc admin mbaas create`
`fhc admin mbaas update`
There was not really a lot to do other than add some doc and examples. The properties are already sent and supercore will use `req.body` to populate the MBaaS target fields.
ping @wei-lee @wtrocki @paolobueno
> RHMAP-6186 allow to set the editable flag in fhc

- package.json
Undo the change made in "publishConfig" for [RHMAP-6397](https://issues.jboss.org/browse/RHMAP-6397)
> Reverts npm publish tag to "latest-2".

- lib/cmd/fh3/appdata.js
Use the `fhc appdata download` command to download the exported file.
No version bump because one version bump for the whole feature branch should be enough.
ping @odra
> RHMAP-6497 download file

- lib/cmd/fh3/appdata/export/read.js
- lib/cmd/fh3/appdata/export/start.js
- lib/cmd/fh3/appdata/export/status.js
- npm-shrinkwrap.json
- package.json
- sonar-project.properties
Create `read` and `status` commands for appdata export in fhc. `read` will just return the job definition as JSON. `status` will do a realtime polling of the job status until it's finished or the user aborts. The syntax is:
`fhc appdata export read`
`fhc appdata export status`
`status` will print and update a progress bar. I decided to use the not-so-fance `progress` packate instead of the more-fance `node-progress-bars` because the former one does not have any additional dependencies.
ping @odra @paolobueno @wei-lee
> RHMAP-6712 add export read and status commands

- lib/cmd/fh3/appdata/export/start.js
- npm-shrinkwrap.json
- package.json
- sonar-project.properties
The `start` command prompts the user wether the app should be stopped before exporting or not. This should be overridable by passing a flag (`--stopApp`) to not interfere with automation.
Also the commands should honor the `--json` flag where applicable (`list` and `read`). This is already given (`read` always returns json).
ping @wei-lee
> RHMAP-6917 make stopApp overridable in the appdata export start command

- lib/common.js
- npm-shrinkwrap.json
- package.json
- sonar-project.properties
The `Download URL` and `Expires` columns should not be shown in the output. The `Download URL` is not useful and the `Expires` contained hardcoded data (and will only make sense once the file-cleanup job is in place.
ping @wei-lee @ziccardi
> RHMAP-7117 remove url and expires cols

- lib/cmd/fh3/appdata/export/status.js
- npm-shrinkwrap.json
- package.json
- sonar-project.properties
When an error was returned from mbaas during the polling of the status of an export job, the polling was interrupted, but no error message was visualized.
> RHMAP-7316

- Gruntfile.js
- README.md
- package.json
- po/fh-fhc.pot
New task that may affects the workflow would be 'potupload'.
Once all string changes is frozen, this task would works to upload
the source strings file in the gettext format to the Zanata server,
the web-based translation platform. and can ask translators
to get it in various languages. once it has been done or time to
make a new release, 'dist' task would pulls the latest translations
from the Zanata server to include them in the release.
Note that uploading into the Zanata server requires an account on it
and zanata.ini file with the API key to automate the process.
> Add a task to push/pull POT/PO files to/from the Zanata server

- lib/cmd/common/build.js
@wei-lee @pb82 
[RHMAP-4442](https://issues.jboss.org/browse/RHMAP-4442)
moved   `args.privateKeyPass = args.keypass;` line so its ran for every build type
probably will need rebase with version bump after other fhc PRs are merged
> Rhmap 4442 fhc keypass parameter does not work for fhc build ios debug

- lib/cmd/fh3/admin/environments/create.js
- lib/cmd/fh3/admin/environments/update.js
- lib/utils/mbaas-token-check.js
- package.json
- test/fixtures/admin/fixture_mbaas.js
- test/unit/fh3/admin/test_environments_commands.js
Currently the environment commands do not accept the `token` which
will soon be used while creating environments.
This adds the `token` option to the `create` and `update` commands.
An example of creating an environment is now as follows:
```
fhc admin environments create --id=example --label=example --target=OpenShiftTarget --token=example
```
* Point fhcap at a cluster. 
- For example, `fhcap target http://testing.eng1.skunkhenry.com/ <username> <password>`
* Create an environment and ensure token is sent in payload using `Wireshark` or something.
- For example, `fhcap admin environments create --id=rhmap9554 --label=rhmap9554 --target=osm3 --token=<token>`
* Update an environment and ensure token is sent in payload using `Wireshark` or something.
- For example, `fhcap admin …
> RHMAP-9554 Update environment commands to accept token

- lib/utils/mbaas-token-check.js
- npm-shrinkwrap.json
- package.json
- sonar-project.properties
Currently when an environment is created through `fhc` the corresponding
environment project is not created.
This is because of the missing `targetType` key on the request to `fh-supercore`.
This adds the `targetType` of `openshift3` when the mbaas is discovered to have
been an OpenShift 3 on in the pre-request check.
> RHMAP-10037 Fix environment project creation in OpenShift

- lib/genericCommand.js
- lib/utils/error-handler.js
- lib/utils/request.js
- npm-shrinkwrap.json
- package.json
- sonar-project.properties
- test/fixtures/appforms/fixture_data_sources.js
- test/fixtures/appforms/fixture_env_forms.js
- test/unit/fh3/appforms/data_sources/test_data_sources.js
- test/unit/fh3/appforms/test_env_forms.js
When a user gets an error back from the platform, it would be useful to display the Request ID associated with the error. 
This will help with debugging.
- The error printed to the console in cli-mode will include the request ID
- The error returned when used as a module will return a request ID as part of the error.
> Add Request ID To Error Output

- lib/cmd/fh3/admin/logs/syslogs.js
- lib/cmd/fhc/login.js
- lib/common.js
- lib/utils/fhlogin.js
- npm-shrinkwrap.json
- package.json
- sonar-project.properties
- test/fixtures/admin/fixture_logs.js
- test/unit/fh3/admin/logs/test_syslogs.js
This command allows users to search for logs based on a request ID. This will also be very useful for fh-uart for collecting logs for failing requests.
- Added a new command `fhc admin logs syslogs` to allow users to search for logs.
> Rhmap 10014 add request logs search command

- lib/commandTree.js
Editor creates a backup file on editing or there may be some garbage
files under the command tree directories unexpectedly. fhc command
should ignores them on looking up commands.
> Do not look up the non-JS files

- lib/utils/mbaas-token-check.js
- package.json
To keep our api consistent we should always sent the same format of data. In current implementation we were missing `targetType` field when type was different than openshift3.
> RHMAP-10713 - fhc environment update improvement

- lib/cmd/common/build.js
in the 'build' command snippet for build.usage.ngui, some of the params were incorrectly named
'branch' should be 'git-branch',  'commit' should be 'git-commit', and 'git-tag' was omitted.
> Fixing typos in the 'build' command snippet

- doc/fh3/admin/mbaas/create.md
- doc/fh3/admin/mbaas/update.md
- lib/cmd/fh3/admin/mbaas/create.js
- lib/cmd/fh3/admin/mbaas/update.js
https://issues.jboss.org/browse/RHMAP-10901
* Following task is to remove demanding of unnecessary parameters when creating OS3 MBaaS Target (cc @PhilipGough )
* When running `fhc admin mbaas create`, the **Usage** does not look good - will be worth to do something about it?
@wtrocki @PhilipGough @aidenkeating Guys, do you have a few minutes for a review?
> RHMAP-10946 Updated help for MBaaS creation

- lib/cmd/fh3/app/_baseCloudRequest.js
- lib/cmd/fhc/target.js
- npm-shrinkwrap.json
- package.json
- sonar-project.properties
Some of the older commands in FHC where using the `request` library directly (and not through `fhreq`) and they were not sendind the `User-Agent` header when calling millicore. The `User-Agent` must be set to `FHC`, in order to skip the CSRF check.
ping @wei-lee @pmdarrow @laurafitzgerald @JameelB
> RHMAP-11075 add User-Agent header

- LICENSE
The FHC tool needs an OSS license. Changed to Apache2 license.
> RHMAP-8199 - Update License of FeedHenry CLI

- lib/cmd/fhc/target.js
- package.json
- sonar-project.properties
For some odd reason, we call `/box/srv/1.1/act/sys/auth/logout` to check Millicore is alive during an `fhc target`.
This change calls the the `/box/srv/1.1/tst/version` EP instead for liveness.
> Ping Millicore for target health check

- CHANGELOG.md
- doc/common/admin-users.md
- lib/cmd/common/admin-users.js
**JIRA:** https://issues.jboss.org/browse/FH-2850
This will allow a comma separated list of team ids when creating a new user e.g. `fhc admin-users create username=testuser email=testuser@test.com teams=5783b4d706bb371b0960eff9,5783b21b0fd0211e09f218e9`
@david-martin A have a concern, is there any more documentation that needs to be modified for users to be aware of how to use this change.
> FH 2850 - Team assignment on creation of user

- LICENSE
Changing to an ASL license may have legal implications, particularly if there are community contributions.
Reverting back to already OSS MIT style license
> Revert to MIT license

- package.json
Use latest by default when publishing package. 
Latest tag is used by default, but I wanted to leave it for informational purposes.
> FH-2853 - Change publish label to latest

- lib/cmd/common/version.js
Change version tag from latest-2 to latest as we no longer support latest-2. 
Without that change fh-fhc would always show that the latest version is outdated. 
Suggestion is to merge this and release it with some other changes.
> Change npm tag in version command

- Gruntfile.js
Zatana changes are breaking build, prevents numerous PR's from being merged. 
Removing them for now. 
@tagoh @jasonmadigan - Feel free to reopen ticket, provide better implementation for this. 
It looks like we aren't able to call zatana translation service and build is timing out. 
Reverting this PR:
https://github.com/feedhenry/fh-fhc/pull/217
> Remove zanata changes 

- lib/cmd/fh3/admin/domains.js
- lib/cmd/fh3/admin/status.js
**Motivation:** https://issues.jboss.org/browse/RHMAP-3862
Updated admin domains args validation to return usage if no options are passed
Updated admin status args validation to return usage if no options are passed
> Rhmap 3862 admin domains help not rendered

- lib/cmd/common/import.js
**Motivation:** https://issues.jboss.org/browse/RHMAP-12418
- Updating request payload to add mandatory options. (`imported ` & `repoBranch `)
- Also updated working result to be more user-friendly. Previously it just returned a large json object.
> Rhmap 12418 cloud app import not working

- lib/cmd/fh3/projects.js
Motivation - https://issues.jboss.org/browse/FH-2993
Usage changes from `fhc projects list` to `fhc projects [list] [<author-email>]`
**Example**: `fhc projects list amoran@redhat.com`. 
This will only return all the projects where the `authorEmail` is `amoran@redhat.com`
> FH 2993 filter projects by user

- lib/cmd/fhc/login.js
Motivation - https://issues.jboss.org/browse/FH-2884
Updated the login error with some useful text.
**Before**
```
fhc ERR! Error: login failed: undefined
fhc ERR! Request ID:  3f17adaa-eb4d-481a-9a54-4b1a25f398db
fhc ERR!
fhc ERR! System Darwin 16.0.0
fhc ERR! command "/Users/amoran/.nvm/versions/node/v4.4.3/bin/node" "/Users/amoran/.nvm/versions/node/v4.4.3/bin/fhc" "login"
fhc Command executed with error
```
**After**
```
fhc ERR! Error: There was an error with your Username/Password combination. Please try again.
fhc ERR! Request ID:  091d59fa-f4d7-49f4-9635-df4110f71b06
fhc ERR!
fhc ERR! System Darwin 16.0.0
fhc ERR! command "/Users/amoran/.nvm/versions/node/v4.4.3/bin/node" "/Users/amoran/Work/fh-fhc/bin/fhc.js" "login"
fhc Command executed with error
```
> Fh 2884 remove undefined login error

- lib/cmd/common/admin-policies.js
**Motivation:** https://issues.jboss.org/browse/FH-2996
No changes to the payload or request. Allowing `MBAAS` to be a valid type and update usage with example
> FH-2996 Allowing type MBAAS for fhc admin-policies create

- lib/cmd/common/admin-policies.js
** Motivation:**https://issues.jboss.org/browse/RHMAP-10385
- Updated admin policies update args validation to only count mandatory args.
- Updated update function with the correct amount of args
> Rhmap 10385 admin policies update incorrect args length

- lib/cmd/fh3/app/stage.js
**Motivation:** https://issues.jboss.org/browse/RHMAP-6059
Updated fhc app stage to use HEAD if no git hash is passed (as per the usage).
How to test:
- Create a test tag: `git tag -a test -m "Test tag"` and push it.
- fhc app stage --app=<appid> --env=dev --gitRef.type=tag --gitRef.value=test
> Rhmap 6059 stage always deploys master

- lib/cmd/common/clusterprops.js
Running `fhc clusterprops` by itself will display the following output, indicating that it's a subcommand of the `admin` command:
```
$ fhc clusterprops
fhc ERR! Invalid action: undefined
fhc ERR! Usage:
fhc ERR!  fhc admin clusterprops list
fhc ERR!  fhc admin clusterprops read <name>
fhc ERR!  fhc admin clusterprops update <prop> <value>
fhc ERR!  fhc admin clusterprops create <prop> <value>
fhc ERR!  fhc admin clusterprops delete <prop>
fhc Command executed with error
```
Then trying to use it as a subcommand of the `admin` command will fail as follows:
```
$ fhc admin clusterprops list
fhc ERR! Error: Command not found: clusterprops
fhc ERR!
fhc ERR! System Linux 4.8.14-300.fc25.x86_64
fhc ERR! command "/home/grdryn/.nvm/versions/node/v4.6.0/bin/node" …
```
> 🐛 Fix inline help for clusterprops command

- lib/cmd/common/configuration.js
This fixes listing of destinations for command `fhc configuration <app-id> all`
@david-martin Hi, got a minute for a review?
> Removed unused destination for fhc configuration

- doc/common/configuration.md
- package.json
Verify with `fhc configuration <app-id> all`
Hey @david-martin, got another minute? :)
I forgot to version bump and docs update. Many thanks!
> Removed deprecated destination from docs

- lib/cmd/fh3/projects.js
- package.json
- sonar-project.properties
https://issues.jboss.org/browse/RHMAP-13185
`fh-ngui` filters `appTemplates` in project templates to only include templates which have `selected: true`. Implementing this same logic here to behave like NGUI in fh-fhc.
> Like fh-ngui, only create appTemplates which are selected

- .gitignore
- Dockerfile
- README.md
- package.json
Adding a `Dockerfile` for FHC. This will simplify further the environment requirements for `fh-cup`.
Some commands for testing:
```
docker run -v $HOME:/root -it feedhenry/fhc target https://rhmap.cup.feedhenry.io
docker run -v $HOME:/root -it feedhenry/fhc login username password
docker run -v $HOME:/root -it feedhenry/fhc projects
```
> Adding a Dockerfile

- package.json
JIRA: https://issues.jboss.org/browse/FH-3458
Public Issue: https://github.com/feedhenry/fh-fhc/issues/297
Following Local Test
```
Camilas-MacBook-Pro:fh-fhc cmacedo$ fhc target
fhc ERR! unsupported version 
fhc ERR! unsupported version fhc requires node version: >=0.10 <= 4.4
fhc ERR! unsupported version And you have: v4.5.0
fhc ERR! unsupported version which is not satisfactory.
fhc ERR! unsupported version 
https://support.us.feedhenry.com/
Camilas-MacBook-Pro:fh-fhc cmacedo$ ./bin/fhc.js target
(node) sys is deprecated. Use util instead.
https://support.us.feedhenry.com/
```
> FH-3458 - Remove block to use fhc with upper versions

- lib/cmd/fh3/admin/status.js
- lib/common.js
- test/fixtures/admin/fixture_status.js
- test/unit/fh3/admin/test_status.js
JIRA: https://issues.jboss.org/browse/RHMAP-15721
Changes:
* Fix the command. It was not working before
* Add it into the V3 standard 
* Add unit test
* Improve output
Following local test 
Following the local test with --json flag
```
Camilas-MacBook-Pro:fh-fhc cmacedo$ ./bin/fhc.js admin status --json
(node) sys is deprecated. Use util instead.
{
"status": "ok",
"summary": {
"amqp": "ok",
"db": "ok",
"cache": "ok",
"git": "ok"
}
}
```
Following the local test to check the help.
````
Camilas-MacBook-Pro:fh-fhc cmacedo$ ./bin/fhc.js help admin status
(node) sys is deprecated. Use util instead.
Usage:
fhc admin status [--json=<json>]
Examples:
fhc admin status           Check status of this domain/millicore
fhc admin status --json    Check status of this domain/millicore with the output as …
```
> RHMAP-15721-Fix command `admin status` and add it to V3 standard with unit tests

- lib/utils/exec.js
- lib/utils/log.js
- lib/utils/output.js
- lib/utils/sys.js
JIRA: https://issues.jboss.org/browse/FH-3616
Following the local test.
> FH-3616 - Remove the Warn: sys is deprecated. Use util instead. from FHC tool

- lib/cmd/fh3/app/read.js
- lib/cmd/fh3/clone.js
JIRA: https://issues.jboss.org/browse/RHMAP-15723
Following the changes made.
* Add it to the V3 standard
* Remove call to use the V2 command. Use the same command but V3 
* Fix output
* Fix description test of the `fhc app read` command which is used here. 
Following local tests
Test when the clone is made.
`````
Camilas-MacBook-Pro:fh-fhc cmacedo$ ./bin/fhc.js clone invchzzwmwnpwehmy54roimi invchzy3wemcaef2lokcayzd 
(node) sys is deprecated. Use util instead.
Cloning into 'TestAllHello-Cloud-App'...
##########################################################################
##########################################################################
Camilas-MacBook-Pro:fh-fhc cmacedo$ 
``````
Test when the app was already cloned.
``````
Camilas-MacBook-Pro:fh-fhc cmacedo$ ./bin/fhc.js …
```
> RHMAP-15723 - Add command `fhc clone` to V3 standard

- lib/cmd/fh3/ping.js
- test/fixtures/fixture_ping.js
- test/unit/fh3/test_ping.js
JIRA: https://issues.jboss.org/browse/RHMAP-15725
Following the changes made.
* Add it into the V3 standard
* Add unit test
Following local test when the cloud app is started.
`````
Camilas-MacBook-Pro:fh-fhc cmacedo$ ./bin/fhc.js ping invchzy3wemcaef2lokcayzd dev
(node) sys is deprecated. Use util instead.
"OK"
Camilas-MacBook-Pro:fh-fhc cmacedo$ 
``````
Following the local test when the cloud app is stoped.
`````
Camilas-MacBook-Pro:fh-fhc cmacedo$ ./bin/fhc.js ping invchzy3wemcaef2lokcayzd dev
(node) sys is deprecated. Use util instead.
fhc ERR! Non 2xx response "Service unavailable, check service exists and is running ok - { [Error: connect ECONNREFUSED 172.22.0.5:8201]
fhc ERR!   code: 'ECONNREFUSED',
fhc ERR!   errno: 'ECONNREFUSED',
fhc ERR!   syscall: 'connect',
fhc ERR! …
> RHMAP-15725 - Add command `fhc ping` to V3 standard and add unit test

- lib/cmd/fh3/app/runtimes.js
- lib/cmd/fh3/app/stage.js
- test/unit/fh3/app/test_runtimes.js
JIRA: https://issues.jboss.org/browse/RHMAP-16184
The command runtime was with the environment fixed as dev. We catcher this error via the automated tests. 
Following the local test after this fix. 
** Verify Steps **
- Go to https://testing.zeta.feedhenry.com/
- take any cloud app id
- Run the command `fhc runtimes` for this app and any environment
> RHMAP-16184 - Command fhc runtimes is with the dev environment fixed

- lib/utils/ini.js
Sometimes we may not have permission to access the home directory, e.g when running FHC on RHMAP. This will allow users to set a custom directory for configs.
JIRA: https://issues.jboss.org/browse/RHMAP-16644
> Custom home directory support

- lib/cmd/fh3/resources/list.js
- package.json
- sonar-project.properties
- test/unit/fh3/resources/test_resources.js
This command was not working on the previous version and it is missing the latest one. 
JIRA: https://issues.jboss.org/browse/FH-3789
**Observation**: The rest service called is not working. 
Internal RHMAP JIRA to fix it is https://issues.jboss.org/browse/RHMAP-17007
> FH-3789 - fhc is missing the command resources list command

- lib/cmd/common/apps.js
- package.json
- sonar-project.properties
JIRA: https://issues.jboss.org/browse/RHMAP-16944
Motivation: Just remove the description about the word list be optional.
Following the local test
```
dhcp-17-108:fh-fhc cmacedo$ ./bin/fhc.js apps 
fhc ERR! 
fhc ERR! fhc apps list <project-id>
fhc ERR! fhc apps create <project-id> <app-title> [<template-id>]
fhc ERR! fhc apps create <project-id> <app-title> <template-type> <git-repo> [<git-branch>]
fhc ERR! fhc apps read <project-id> <app-id>
fhc ERR! fhc apps update <project-id> <app-id> <property-name> <property-value>
fhc ERR! fhc apps delete <project-id> <app-id>
fhc Command executed with error
dhcp-17-108:fh-fhc cmacedo$ 
```
> fhc apps [list] command is not accepting optional word list

- lib/cmd/fh3/credential/create.js
- lib/utils/request.js
JIRA: https://issues.jboss.org/browse/FH-3411
**Steps to verify**
```
$ ./bin/fhc.js fhcfg set proxy <proxy>
$ ./bin/fhc.js admin-storeitems uploadbinary 5w477lfgy3jrnovri7gctsb7 android test.txt 
$ ./bin/fhc.js import pxfgryzid25qgz3g3nmgmufc testZip client_advanced_hybrid /Users/cmacedo/Desktop/ios-7.0-2-CordovaApp-src.zip 
```
> FH-3411 - fh-fhc upload app binary does not use proxy setting

- lib/cmd/fh3/projects/create.js
- npm-shrinkwrap.json
- package.json
- sonar-project.properties
- test/unit/fh3/test_ping.js
Perform the same implementation made into the PR https://github.com/feedhenry/fh-fhc/pull/295/files in order to create the new project with no all client applications select either as it is made by default into NGUI.
JIRA: https://issues.jboss.org/browse/RHMAP-17444
**Local Test:**
```
dhcp-16-185:fh-fhc cmacedo$ ./bin/fhc.js projects create --title=CamilaTest --template=hello_world_project
Project 'CamilaTest' create successfully
```
**Steps to Verify:** 
Create a new project in a domain with the template "hello_world_project".
> Rhmap 17444 - "Not 2xx status" when creating hello_world_project via fhc

- lib/cmd/fh3/app/create.js
Add some help text for app types
`fhc app create --help`
Before:
```
Options:
--project, -p  Unique 24 character GUID of the project you want this app to be created in.                                                                                                                                               [required]
--type         The type of app.
```
```
Options:
--project, -p  Unique 24 character GUID of the project you want this app to be created in.                                                                                                                                               [required]
--type         The type of app. Choose from:
- cloud_nodejs (Node.js App)
- client_advanced_hybrid (Cordova)
- client_native_ios (Native iOS)
- client_native_android (Native Android)
- …
```
> Adding app types help

- CHANGELOG.md
- lib/cmd/fh3/app/updateConfig.js
- package.json
- po/fh-fhc.pot
- test/unit/fh3/app/test_app.js
This command could not have been used, as the folder where it was places was named `update` and fhc called `update.js` instead.
> Moved config.js out of folder and renamed to updateConfig.js

- lib/cmd/fh3/admin/appstore/storeitems/add.js
- npm-shrinkwrap.json
- package.json
- sonar-project.properties
- test/unit/fh3/admin/appstore/test_storeitems.js
**Motivation**
The command to add a store item[1] related to the point is missing after apply the V3 standard,
improve the outputs and add the unit tests into the PR [2]. This PR is in order to add the missing command which has the endpoint [3]
**Local tests**
```
camiladeomacedo@Camilas-MBP ~/redhat/fh-fhc (RHMAP-19611) $ ./bin/fhc.js  admin appstore storeitems add --id=3v4qjzyktlnfvevje5unoqgb
Item Store added successfully.
camiladeomacedo@Camilas-MBP ~/redhat/fh-fhc (RHMAP-19611) $ ./bin/fhc.js  admin appstore storeitems add --id=3v4qjzyktlnfvevje5unoqgb --json
{
"status": "ok"
}
camiladeomacedo@Camilas-MBP ~/redhat/fh-fhc (RHMAP-19611) $ 
```
[1] - https://github.com/feedhenry/fh-fhc/commit/9ae4cc6f4f1007cf19a0829903ecd29e3bf9b5f9#diff-bb7c1835b9d57a46ca5f53d0201d08ebL84
[2] - …
> RHMAP-19611 - Adding missing command 'fhc admin appstore storeitems add --id=<id>'

- CHANGELOG.md
- lib/cmd/fh3/keys/user/add.js
- npm-shrinkwrap.json
- package.json
- sonar-project.properties
- test/unit/fh3/keys/user/test_user.js
*Motivation* 
The command "fhc keys user add <label>" is missing in the latest version of FHC.
* Ref.: https://github.com/feedhenry/fh-fhc/pull/376/files#diff-e7ea873a0f36f8c16cdeac0455853567L6
* Documentation : https://access.redhat.com/documentation/en-us/red_hat_mobile_application_platform_hosted/3/html/local_development_guide/local-development-guide-working-with-the-platform-using-fhc#managing-api-keys-with-fhc
*Local Test* 
```
cmacedo@camilas-MacBook-Pro ~/work/fh-fhc (RHMAP-19710) $ ./bin/fhc.js keys user add test --json
{
"apiKey": {
"key": "4a2341a65c709e5fa4a1a901dda21b0a88b0ec9e",
"keyReference": "i4ze7ruomd27wnohth22to4v",
"keyType": "user",
"label": "test",
"revoked": null,
"revokedBy": null,
"revokedEmail": null
},
"status": "ok"
}
cmacedo@camilas-MacBook-Pro ~/work/fh-fhc …
```
> RHMAP-19710 - The command "fhc keys user add <label>" is missing in the latest version of FHC

- CHANGELOG.md
- lib/cmd/fh3/eventalert/create.js
- npm-shrinkwrap.json
- package.json
https://issues.jboss.org/browse/RHMAP-20967
* Fix success output when an alert is created for in a decoupled MBaaS
* All decoupled MBaaS will return an empty body.
* 4.X use just decoupled MBaaS
If it came back a data show a table if not shows that was created with success. 
1. Run `./bin/fhc.js target <domain>` ( e.g ` bin/fhc.js target https://rhmap.osm1.skunkhenry.com/`)
2. Run `./bin/fhc.js login`
3. Run `./bin/fhc eventalert create --app=<app> --name=<name> --categories=<categories>
--severities=<severities> --events=<events> --emails=<emails> --env=<env>`  ( E.g `./bin/fhc.js eventalert create --app=r6ghddievqzumnsq2djvtruv --name=test --categories=APP_ENVIRONMENT --severities=INFO --events=CHANGE_REQUESTED --emails=test --env=dev` ) 
``` javascript
$ ./bin/fhc.js eventalert create …
```
> fix(RHMAP-20967): Unable to create alerts via fhc

- CHANGELOG.md
- lib/cmd/fh3/build.js
- lib/cmd/fh3/ups/variant/add.js
- lib/cmd/fh3/ups/variant/delete.js
- npm-shrinkwrap.json
- package.json
- po/fh-fhc.pot
https://issues.jboss.org/browse/RHMAP-21057
Remove Windows feature/options
Windows feature are not so long supported. 
- Remove windows option/type to build apps
- Remove windows type from UPS commands 
- Update translations via `grunt potupload` task
- Run the command `./bin/fhc.js build` and check if the windows options/type will appears
```
cmacedo@camilas-MBP ~/work/fh-fhc (RHMAP-21057) $ ./bin/fhc.js build
Usage:
fhc build --project=<project> --app=<app> --cloud_app=<cloud_app> [--tag=<tag>]
--environment=<environment> --destination=<destination> [--version=<version>]
[--config=<config>] [--privateKeyPass=<privateKeyPass>] [--certpass=<certpass>]
[--download=<download>] [--bundleId=<bundleId>]
[--cordova_version=<cordova_version>] [--git-tag=<git-tag>]
[--git-branch=<git-branch>] …
```
> task(remove windows feat): RHMAP-21057 

- CHANGELOG.md
- npm-shrinkwrap.json
- package.json
https://issues.jboss.org/browse/RHMAP-21472
The task of `grunt potupload` fails.
This happens due to the changes of the Zanata REST APIs.
newer zanata-js and grunt-zanata-js fixes this issue and just need to update the deps of library for them.
run `grunt potupload`
> Update deps of grunt-zanata-js to fix potupload task

- CHANGELOG.md
- lib/cmd/fh3/services/create.js
- npm-shrinkwrap.json
- package.json
No JIRA, I have just found it while doing preliminary testing of fhc before 4.7.0 is cut.
Alias for title and template cannot be the same.
Because then the input parameters are not processed properly
Fixed by changing the alias for template from 't' to 'p'
All these commands should create the service successfully. Preferably use node10 or node8.
fhc services create --title=yourtitle
fhc services create --title=yourtitle-01 --template=new-service
fhc services create -t=yourtitle-03 -p=new-service
fhc services create yourtitle-04 new-service
You can optionally run our fh-art test suite
https://github.com/fheng/fh-art
command to trigger it locally:
grunt test-core:core --prefix yourprefix- --coreusername yourusername --corepassword yourpassword --corehost https://your.rhmap.domain.com
- [ x] …
> Fixed alias for template in fhc services

- CHANGELOG.md
- npm-shrinkwrap.json
- package.json
https://issues.jboss.org/browse/RHMAP-21483
Fix the following issue with the production version which appears after install via $sudo npm install fh-fhc -g.
```
/Users/camilamacedo/.nvm/versions/node/v6.14.4/lib
└── fh-fhc@7.1.0-1 
camilamacedo@Camilas-MacBook-Pro ~ $ fhc
module.js:478
throw err;
^
Error: Cannot find module 'colors'
at Function.Module._resolveFilename (module.js:476:15)
at Function.Module._load (module.js:424:25)
at Module.require (module.js:504:17)
at require (internal/module.js:20:19)
at Object.<anonymous> (/Users/camilamacedo/.nvm/versions/node/v6.14.4/lib/node_modules/fh-fhc/lib/fhc.js:3:14)
at Module._compile (module.js:577:32)
at Object.Module._extensions..js (module.js:586:10)
at Module.load (module.js:494:32)
at tryModuleLoad (module.js:453:12)
at …
```
> Fix publish

- CHANGELOG.md
- npm-shrinkwrap.json
- package.json
https://issues.jboss.org/browse/RHMAP-21634
Upgrade request and yargs dependency libs regard CEVs
- To solve CEVs
* `npm install --save --save-exact yargs@12.0.1`
* `npm install --save --save-exact request@2.88.0`
Check if the CI will finish with success since both libs did not have breakages and their usage in implicitly in all commands of this projects which is quite covered by the test.
> RHMAP-21634-  Upgrade request and yargs dependency libs regards CEVs

- CHANGELOG.md
- lib/cmd/fh3/connections/create.js
- npm-shrinkwrap.json
- package.json
https://issues.jboss.org/browse/RHMAP-21897
Add command to create connections
In order to be helpful when the BF be deprecated
New command to use the same REST API used by RHMAP studio
```
$ ./bin/fhc.js connections
No action specified. Usage: 
fhc connections <action>
Where <action> is one of:
create             	Create connections
list               	List connections
read               	Read a connection
update             	Update connections
```
```
./bin/fhc.js connections create
Usage:
fhc connections create --client=<client> --cloud=<cloud> --type=<type>
--env=<env> --project=<project> [--connection=<connection>] [--json=<json>]
Options:
--help            Show help                                          [boolean]
--version         Show version number …
```
> RHMAP-21897: Add create connections command
